# Class 5: NumPy
## Objective: Learn the fundamentals of NumPy

**Instructions:** Work with one or more students at your table. Discuss the key concepts and the code logic with one another. 

In [1]:
# The 'nickname' np is nearly univerally used for the numpy package.
import numpy as np
# The time module is useful for measuring efficiency
import time

print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.5


## Section 1: Why NumPy? Speed and Vectorization

Python lists are flexible but slow because they are "objects" that require type-checking at every step (for every element). ```NumPy``` arrays are fixed-type and stored in contiguous memory, allowing for Vectorization (performing operations on whole arrays without for loops).

In this demonstration, we create some example data with ```np.arange()```, which like ```range()```, but it creates a ```NumPy``` array rather than a list.

fig, ax = plt.subplots()
ax.plot(times, magnitudes)
ax.xlabel('Time (days)')

In [1]:
fig, ax = plt.subplots()
ax.plot(times, magnitudes)
ax.xlabel('Time (days)')


NameError: name 'plt' is not defined

**Test your understanding:** Create an array of 1,000,000 random star magnitudes using ```np.random.uniform(0, 20, 1000000)```. 
Then use a vectorized operation to convert all of them to flux using the formula 
$$ flux=10^{−0.4×mag}.$$ Time how long it takes!

In [7]:
# Here is how to create the array
mags = np.random.uniform(0, 20, 1000000)

# Here is timing for the standard (loop) approach
start = time.time()
flux = [10**(-0.4*m) for m in mags]
print(f"Python Loop Time: {time.time() - start:.4f}s")

# Enter your code here for the vectorized version


Python Loop Time: 0.6715s
NumPy Vectorized Time: 0.0001s


## Section 2: Array Creation and Properties
Astronomers use different "grids" for different tasks: ```linspace``` for spectra, ```logspace``` for mass functions, and ```zeros``` for image templates.

You can specify the data type ```dtype``` when you create the array. This has implications for how much memory an array requires, which in turn impacts the efficiency of calculations.

In [ ]:
# Topic: Creation methods and Array properties (shape, ndim, dtype)
grid = np.linspace(3800, 7500, 1000)  # 1000 points from 3800A to 7500A (Visible spectrum)
image = np.zeros((1024, 1024), dtype='float32') # A blank CCD frame

print(f"Spectrum Shape: {grid.shape}")
print(f"Image Data Type: {image.dtype}")
print(f"Number of Pixels: {image.size}")

# Check the precision and range limits:
print(f"np.int16 can store: {np.iinfo(np.int16).min} to {np.iinfo(np.int16).max}")
print(f"np.float32 can store: {np.finfo(np.float32).min} to {np.finfo(np.float32).max}")

**Test your understanding:** Create a 3D array representing a "Data Cube" (e.g., 2D images over time) with shape (10, 512, 512) filled entirely with the number 1.0. Use ```.astype()``` to change its type to ```int16```.

In [9]:
# Enter your code here: 
data_cube = np.ones([10, 512, 512])
data_cube_int = data_cube.astype(dtype=np.int16)
data_int_int

## Section 3: Indexing, Slicing, and Views
Indexing in 2D follows [```row, column```]. 

Array slicing has the syntax [```start:stop:step```]. 

Remember: Slicing creates a "View", not a copy. If you change a slice, the original array changes.

In [8]:
# Topic: 2D Indexing and Views vs Copies
data = np.random.normal(100, 5, (10, 10)) # Simulated 10x10 star cluster image
print("\nOriginal")
print(data[0:4, 0:4])
# Slice a 3x3 sub-section (a "postage stamp")
sub_section = data[0:3, 0:3]

# Modify the sub-section
sub_section[:] = 0

print("\nOriginal again")
# Check the original data - notice the top corner is now 0
print(data[0:4, 0:4])


Original
[[100.83543163  94.25900299  99.72971625 108.59651102]
 [ 97.96611959 105.59042381  95.89715013 109.73862923]
 [ 99.53094961  96.98174405 103.0216835   99.21111944]
 [ 99.93982912 101.19629076  95.31022157 103.19028313]]

Original again
[[  0.           0.           0.         108.59651102]
 [  0.           0.           0.         109.73862923]
 [  0.           0.           0.          99.21111944]
 [ 99.93982912 101.19629076  95.31022157 103.19028313]]


**Test your understanding:** Create a 5x5 array of integers from 0 to 24. Extract the "center" 3x3 region using slicing. Use ```.copy()``` so that modifications to the center don't affect the original 5x5 grid.

In [13]:
# You can use np.arange() and then .reshape() to create a 5x5 array:
array = np.arange(25).reshape(5,5)
print(array) 

# Enter your code here: 
center = array[1:4,1:4].copy()
print(center)

center[1,1] = 0
print(center)
print(array)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
[[ 6  7  8]
 [11  0 13]
 [16 17 18]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Section 4: Broadcasting and Matrix Operations

Broadcasting allows you to perform math between arrays of different shapes (e.g., subtracting a single "dark frame" value from every pixel in an image).

A dark frame refers to the amount of flux in each pixel that would be present even if the instrument were not exposed to light. This flux could be due to emission with the detector substrate or light leaking into the instrument. 

In [ ]:
# Topic: Broadcasting and Matrix Multiplication (@)
image = np.ones((5, 5)) * 100
dark_current = 5

# Broadcasting: Subtracting a scalar from a 2D array
calibrated = image - dark_current 

# Matrix Multiplication vs Element-wise
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise (*):\n", A * B)
print("Matrix Multi (@):\n", A @ B)

**Test your understanding:** You have an array of 5 galaxy distances in Mpc: ```dist = np.array([10, 25, 40, 55, 70])```. Use broadcasting to convert the entire array to parsecs (multiply by $10^6$).

In [ ]:
dist_mpc = np.array([10, 25, 40, 55, 70])

# Enter your code here: 


## Section 5: Statistics and Axis Parameters

NumPy can collapse dimensions to find averages across rows (stars) or columns (time).

In [ ]:
# Topic: Statistics, Axis, and Percentiles
# 4 stars observed over 5 nights
observations = np.random.normal(15, 0.2, (4, 5))
print(f"observations = {observations}") 

# Mean brightness for EACH star (average across nights)
star_means = np.mean(observations, axis=1)

# Median and Percentiles (Percentile is great for clipping outliers)
med = np.median(observations)
upper_limit = np.percentile(observations, 95)

print(f"Mean of each star: {star_means}")
print(f"95th percentile value: {upper_limit}")

**Test your understanding:** Using the ```observations``` array above, calculate the standard deviation (```np.std```) for each night (across all stars). Which axis should you use?

In [ ]:
# Enter your code here: 


## Section 6: Masking and np.where()

Boolean indexing (masking) is how astronomers "clean" data by removing bad pixels or selecting stars within a certain magnitude range.

In [ ]:
# Topic: Boolean indexing, np.where, and NaN handling
mags = np.array([12.1, 18.5, np.nan, 14.2, 19.1, 13.8])

# Create a mask for bright stars (mag < 15) and not NaN
mask = (mags < 15) & (~np.isnan(mags))

# Use the mask to extract values
bright_stars = mags[mask]

# np.where: Replace NaNs with a default value (e.g., 99.9)
cleaned_mags = np.where(np.isnan(mags), 99.9, mags)

print(f"Bright Stars: {bright_stars}")
print(f"Cleaned Catalog: {cleaned_mags}")

**Test your understanding:** Find the indices of all magnitudes in ```mags``` that are greater than 18 using ```np.where```. Then, use ```np.argmax()``` to find the index of the single dimmest (largest) magnitude.

In [ ]:
# Enter your code here


**Test your understanding:** You have an array of Signal-to-Noise Ratios (SNR) for a set of observations: ```snr = np.array([5.2, 1.1, 15.6, 0.4, 22.1, 8.9, 2.5, 12.3])```

Create a boolean mask called ```high_quality``` for all values where snr is greater than or equal to 10.

Use that mask to print only the high-quality SNR values.

Bonus: Use ```np.where()``` to create a new array where any SNR below 5 is replaced with the number ```0.0```, but all other values remain the same.

In [ ]:
snr = np.array([5.2, 1.1, 15.6, 0.4, 22.1, 8.9, 2.5, 12.3])
# Enter your code here


## Section 7: Saving and Loading Data

Use ```.npy``` for single arrays and ```.npz``` to bundle multiple associated arrays (like data, errors, and headers).

In [ ]:
# Topic: File I/O (save/load/savez)
# Save multiple arrays into one compressed file
np.savez("star_study.npz", catalog=mags, metadata=grid)

# Load it back
archive = np.load("star_study.npz")
print(archive.files)
print(archive['catalog'])

**Test your understanding:** Save your ```bright_stars``` array from the previous task as a ```.npy``` file. Load it back into a new variable and verify the values are the same.

In [ ]:
# Enter your code here
